using bnoffer.EventMessageBus.Interfaces;

namespace bnoffer.EventMessageBus;

public static class AppBuilderExtensions
{
    /// <summary>
    /// Initializes the mein Event Message Bus
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
    /// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="MessageBus"/></returns>
    public static MauiAppBuilder UseMessageBus(this MauiAppBuilder builder)
    {
        builder
            .Services
                .AddSingleton<IMessageBus, MessageBus>();

        return builder;
    }
}

