using Microsoft.Extensions.Hosting;
using bnoffer.EventMessageBus.Interfaces;
using Microsoft.Extensions.DependencyInjection;

namespace bnoffer.EventMessageBus;

public static class AppBuilderExtensions
{
    /// <summary>
    /// Initializes the mein Event Message Bus
    /// </summary>
    /// <param name="builder"><see cref="IHostApplicationBuilder"/> generated by <see cref="IHostApplicationBuilder"/> </param>
    /// <returns><see cref="IHostApplicationBuilder"/> initialized for <see cref="MessageBus"/></returns>
    public static IHostApplicationBuilder UseMessageBus(this IHostApplicationBuilder builder)
    {
        builder
            .Services
                .AddSingleton<IMessageBus, MessageBus>();

        return builder;
    }
}

