name: Continuous Integration

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./AppMessageBus

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./AppMessageBus
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup nuget
        uses: nuget/setup-nuget@v1
      - name: Restore nuget packages for solution
        run: nuget restore ../EventMessageBus.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: msbuild EventMessageBus.csproj